server:
  port: 8083

spring:
  application:
    name: listing-service

  datasource:
    url: jdbc:postgresql://localhost:5432/listing_db
    username: postgres
    password: your_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true